name: Deploy
on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Documentation update'
        default: 'Doc update'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Checout submodule
      - name: Checkout submodules
        run: git submodule update --init --remote --recursive

      # Install
      - name: Package update
        working-directory: ./demo
        run: npm install

      # Build
      - name: Package build
        working-directory: ./demo
        run: sudo npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: ./demo/src/.vuepress/dist # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
